In [ ]:
import numpy as np
arr1 = np.empty((2, 2))
print("Empty 2x2 Array:\n", arr1)
arr2 = np.ones((4, 2))
print("\nAll ones 4x2 Array:\n", arr2)
arr3=np.full((3, 3), 7)
print("\nFull Array (3x3 filled with 7):\n", arr3)
given_array = np.array([[1, 2, 3],[4, 5, 6]])
arr4 = np.zeros_like(given_array)
print("\nZeros like given array:\n", arr4)
arr5 = np.ones_like(given_array)
print("\nOnes like given array:\n", arr5)
new_list = [1, 2, 3, 4]
arr6 = np.array(new_list)
print("\nList converted to NumPy array:\n", arr6)


Empty 2x2 Array:
 [[1.55252261e-315 0.00000000e+000]
 [1.57061184e-315 6.76217956e-310]]

All ones 4x2 Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Full Array (3x3 filled with 7):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros like given array:
 [[0 0 0]
 [0 0 0]]

Ones like given array:
 [[1 1 1]
 [1 1 1]]

List converted to NumPy array:
 [1 2 3 4]


In [ ]:
import numpy as np
arr1 = np.arange(10, 50)
print("Array 10 to 49:\n", arr1)
arr2 = np.arange(9).reshape(3, 3)
print("\n3x3 Matrix 0 to 8:\n", arr2)
arr3 = np.eye(3)
print("\nIdentity Matrix:\n", arr3)
arr4 = np.random.random(30)
print("\nMean of random array:\n", arr4.mean())
arr5 = np.random.random((10, 10))
print("\nMin:", arr5.min(), " Max:", arr5.max())
arr6 = np.zeros(10)
arr6[4] = 1
print("\nZero array with 5th element = 1:\n", arr6)
arr = np.array([1, 2, 0, 0, 4, 0])
arr7 = arr[::-1]
print("\nReversed array:\n", arr7)
arr8 = np.ones((5, 5))
arr8[1:-1, 1:-1] = 0
print("\n2D array with border 1 and inside 0:\n", arr8)
arr9 = np.zeros((8, 8))
arr9[1::2, ::2] = 1
arr9[::2, 1::2] = 1
print("\n8x8 Checkerboard pattern:\n", arr9)


Array 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 Matrix 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Mean of random array:
 0.5970963135205163

Min: 0.018159216077225926  Max: 0.9904718930485187

Zero array with 5th element = 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

Reversed array:
 [0 4 0 0 2 1]

2D array with border 1 and inside 0:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

8x8 Checkerboard pattern:
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [ ]:
import numpy as np
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])
add_xy = x + y
print("\nAddition of x and y:\n", add_xy)
sub_xy = x - y
print("\nSubtraction of x and y:\n", sub_xy)
mul_x = x * 3
print("\nx multiplied by 3:\n", mul_x)
sq_x = x ** 2
print("\nSquare of each element in x:\n", sq_x)
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print("\nDot product (v . w):", dot_vw)
print("Dot product (x . v):\n", dot_xv)
print("Dot product (x . y):\n", dot_xy)
concat_xy_rows = np.vstack((x, y))
print("\nConcatenate x & y along rows:\n", concat_xy_rows)
concat_vw_columns = np.column_stack((v, w))
print("\nConcatenate v & w along columns:\n", concat_vw_columns)
print("\nAttempting to concatenate x and v:")
try:
    invalid_concat = np.concatenate((x, v))
except ValueError as e:
    print("Error:", e)
    print("Reason: x is 2D but v is 1D — dimensions do not match.")
v_reshaped = v.reshape(1, 2)
valid_concat = np.concatenate((x, v_reshaped))
print("\nCorrect concatenation after reshaping v:\n", valid_concat)



Addition of x and y:
 [[ 6  8]
 [10 13]]

Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]

x multiplied by 3:
 [[ 3  6]
 [ 9 15]]

Square of each element in x:
 [[ 1  4]
 [ 9 25]]

Dot product (v . w): 219
Dot product (x . v):
 [29 77]
Dot product (x . y):
 [[19 22]
 [50 58]]

Concatenate x & y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenate v & w along columns:
 [[ 9 11]
 [10 12]]

Attempting to concatenate x and v:
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Reason: x is 2D but v is 1D — dimensions do not match.

Correct concatenation after reshaping v:
 [[ 1  2]
 [ 3  5]
 [ 9 10]]


In [ ]:
import numpy as np
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

print("Matrix Proofs")
A_inv = np.linalg.inv(A)
A_times_A_inv = np.dot(A, A_inv)
I = np.eye(2)

print("\n1. Prove A * A^-1 = I")
print("Matrix A:\n", A)
print("Inverse of A (A^-1):\n", A_inv)
print("A * A^-1:\n", A_times_A_inv)
print("Identity Matrix I:\n", I)
is_identity = np.allclose(A_times_A_inv, I)
print(f"Is A * A^-1 numerically close to I? {is_identity}")
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\n2. Prove AB != BA")
print("A * B (AB):\n", AB)
print("B * A (BA):\n", BA)
is_not_equal = not np.array_equal(AB, BA)
print(f"Is AB != BA? {is_not_equal}")
AB_T = np.dot(A, B).T
BT_AT = np.dot(B.T, A.T)
print("\n3. Prove (AB)^T = B^T * A^T")
print("(A * B)^T:\n", AB_T)
print("B^T * A^T:\n", BT_AT)
is_equal_transpose = np.allclose(AB_T, BT_AT)
print(f"Is (AB)^T numerically close to B^T * A^T? {is_equal_transpose}")
A_lin = np.array([[2, -3, 1],
                  [1, -1, 2],
                  [3, 1, -1]])
B_lin = np.array([-1, -3, 9]) # B is the column vector of constants

print("\nCoefficient Matrix A:\n", A_lin)
print("Constant Vector B:\n", B_lin)
A_lin_inv = np.linalg.inv(A_lin)
X_inverse = np.dot(A_lin_inv, B_lin)
print("\nSolution using Inverse Method (X = A^-1 * B):")
print("Inverse of A (A^-1):\n", A_lin_inv)
print("Solution Vector X (x, y, z):\n", X_inverse)
print(f"The solution is: x = {X_inverse[0]:.0f}, y = {X_inverse[1]:.0f}, z = {X_inverse[2]:.0f}")
X_solve = np.linalg.solve(A_lin, B_lin)
print("\nSolution using np.linalg.solve(A, B):")
print("Solution Vector X (x, y, z):\n", X_solve)
print(f"The solution is: x = {X_solve[0]:.0f}, y = {X_solve[1]:.0f}, z = {X_solve[2]:.0f}")
B_check = np.dot(A_lin, X_solve)
print("\nVerification (A * X_solve should equal B):\n", B_check)
print(f"Does A * X_solve numerically equal B? {np.allclose(B_check, B_lin)}")

Matrix Proofs

1. Prove A * A^-1 = I
Matrix A:
 [[3 4]
 [7 8]]
Inverse of A (A^-1):
 [[-2.    1.  ]
 [ 1.75 -0.75]]
A * A^-1:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Identity Matrix I:
 [[1. 0.]
 [0. 1.]]
Is A * A^-1 numerically close to I? True

2. Prove AB != BA
A * B (AB):
 [[23 13]
 [51 29]]
B * A (BA):
 [[36 44]
 [13 16]]
Is AB != BA? True

3. Prove (AB)^T = B^T * A^T
(A * B)^T:
 [[23 51]
 [13 29]]
B^T * A^T:
 [[23 51]
 [13 29]]
Is (AB)^T numerically close to B^T * A^T? True

Coefficient Matrix A:
 [[ 2 -3  1]
 [ 1 -1  2]
 [ 3  1 -1]]
Constant Vector B:
 [-1 -3  9]

Solution using Inverse Method (X = A^-1 * B):
Inverse of A (A^-1):
 [[ 0.05263158  0.10526316  0.26315789]
 [-0.36842105  0.26315789  0.15789474]
 [-0.21052632  0.57894737 -0.05263158]]
Solution Vector X (x, y, z):
 [ 2.  1. -2.]
The solution is: x = 2, y = 1, z = -2

Solution using np.linalg.solve(A, B):
Solution Vector X (x, y, z):
 [ 2.  1. -2.]
The solution is: x = 2, y = 1, z = -2

Veri